play2_auth.error.provider_not_found = Provider ''{0}'' was not found - not configured properly?
